version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.32.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
    restart: always
  
  node-exporter:
    image: prom/node-exporter:v1.3.1
    networks:
      - monitoring
    restart: always
  
  grafana:
    image: grafana/grafana:8.3.1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: always



networks:
  monitoring:
    driver: bridge
