global:
  scrape_interval: 15s

scrape_configs:
# Single Job with Single Target
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']


# Single Job with Multiple Target
#  - job_name: 'multiple-node-exporter'
#    static_configs:
#      - targets: ['node-exporter-1:9100', 'node-exporter-2:9100', 'node-exporter-3:9100']


# Single Target on each Multiple Job 
#  - job_name: 'node-exporter-1'
#    static_configs:
#      - targets: ['node-exporter-1:9100']
#         labels:
#           instance: 'node-1'
#  - job_name: 'node-exporter-2'
#    static_configs:
#      - targets: ['node-exporter-2:9100']
#         labels:
#           instance: 'node-2'
#  - job_name: 'node-exporter-3'
#    static_configs:
#      - targets: ['node-exporter-3:9100']
#         labels:
#           instance: 'node-3'
#     basic_auth:
#      username: user
#      password: password
