global:
  scrape_interval: 15s

scrape_configs:
# Single Node with Single Target
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']


# Single Node with Multiple Target
#  - job_name: 'multiple-node-exporter'
#    static_configs:
#      - targets: ['node-exporter-1:9100', 'node-exporter-2:9100', 'node-exporter-3:9100']



# Single Target on each Multiple Node 
#  - job_name: 'node-exporter-1'
#    static_configs:
#      - targets: ['node-exporter-1:9100']
#  - job_name: 'node-exporter-2'
#    static_configs:
#      - targets: ['node-exporter-2:9100']
#  - job_name: 'node-exporter-3'
#    static_configs:
#      - targets: ['node-exporter-3:9100']